server {
    listen 8080;
    server_name _;
    root /var/www/html/web; # Si el index.php está en la raíz, cambia '/var/www/html/web' a '/var/www/html'

    index index.php;

    # Soporte para Clean URLs de Drupal
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesar archivos PHP vía PHP-FPM
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Bloquear acceso a archivos sensibles o privados de Drupal
    location ~ \.(engine|inc|info|install|make|module|profile|test|po|sh|sql|theme|tpl(\.php)?|xtmpl)$ {
        deny all;
    }

    location ~ ^/sites/.*/files/php/ {
        deny all;
    }

    # Optimización de estáticos (imágenes, CSS, JS)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
